[package]
name = "test-paser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

onig = "4"
lazy_static = "0.2.8"